openapi: "3.0.0"
info: 
  title: Linkedin 

  version: "1.0.0"
  description: Linkedin Clone
servers:
  - url: http://localhost:8080
paths: 
  /auth/login:
    post:
      tags:
       - User
      summary: Create a new User
      description: Creates a new user
      requestBody:
        description: Request to create user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: 'Not Found: This response is shown if the request for information is not there or it could not be imported'
        '422':
          description: User credentials not provided
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
        '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
  /auth/signup:
    post:
      tags:
       - User
      summary: Create a new User
      description: Creates a new user
      requestBody:
        description: Request to create user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '409':
            description: Conflict
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: The provided email already exists
        '422':
          description: User credentials not provided
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
        '500':
            description: Internal server error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
  /users:
    put:
      tags:
        - User
      parameters:
        - name: 'User details'
          in: path
          required: true
          description: User details
          example: {name:"username", languages:"Hindi"}
          schema:
            type: object
            format: JSON
      summary: Edit the user
      description: Updates the user
      requestBody:
        description: Request to edit advisor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Advisor updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Advisor edited successfully.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Advisor not found
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided advisorId is not valid, 1234 
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /posts:
    get:
    post:
    put:
    delete:
  /comments:
    get:
    post:
    put:
    delete:
  /reactions:
    get:
    post:
    put:
    delete:

