openapi: "3.0.0"
info: 
  title: Linkedin 

  version: "1.0.0"
  description: Linkedin Clone
servers:
  - url: http://localhost:8080
paths: 
  /auth:
    paths:
      /login:
        post:
          tags:
           - 
      /signup:
        post:
  /users:
    put:
  /posts:
    get:
    post:
    put:
    delete:
  /comments:
    get:
    post:
    put:
    delete:
  /reactions:
    get:
    post:
    put:
    delete:

